version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    working_directory: ~/cobralist
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
      - image: circleci/mariadb:latest
        environment:
          - MYSQL_DATABASE: cobralist
          - MYSQL_USER: cobra
          - MYSQL_PASSWORD: cobrapw
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Flyway Migrate
          command: ./gradlew flywayMigrate
      - run:
          name: Build Project
          command: ./gradlew build
      - run:
          name: Backend Code Coverage
          command: ./gradlew :backend:jacocoRootReport
      - run:
          name: Test Frontend with Code Coverage
          command: |-
            cd frontend/
            npm test --- --watch=false --coverage
      - store_artifacts:
          path:  backend/build
      - codecov/upload:
          file: backend/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          flags: backend
      - store_artifacts:
          path:  frontend/coverage
      - store_artifacts:
          path:  frontend/dist
      - codecov/upload:
          file: frontend/coverage/coverage-final.json
          flags: frontend

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
