spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cobralist?useSSL=false
    username: cobra
    password: cobrapw
    hikari:
      max-lifetime: 58000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  security:
    oauth2:
      client:
        registration:
          spotify:
            clientId: <client-id>
            clientSecret: <client-secret>
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - user-read-private
              - user-read-email
              - playlist-read-private
              - playlist-read-collaborative
        provider:
          spotify:
            authorizationUri: https://accounts.spotify.com/authorize
            tokenUri: https://accounts.spotify.com/api/token
            userInfoUri: https://api.spotify.com/v1/me
            user-name-attribute: display_name
app:
  devMode: true
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBCDFDS926D96C90030DD58429D2751AC1BDBBCDFDS926D96C90030DD58429D2751AC1BDBBCDFDS926D96C90030DD58429D2751AC1BDBBCDFDS926D96C90030DD58429D2751AC1BDBBCDFDS926D96C90030DD58429D2751AC1BDBBCDFDS
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect